replicaCount: 1
image:
  repository: dhruvmistry200/skybyte-app
  tag: v6
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
namespace: devops-challenge
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
