apiVersion: v1
kind: Secret
metadata:
  name: api-token
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "skybyte-app.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.apiToken | b64enc | quote }}